name: C CI

on:
  push:
  pull_request:

jobs:
  build-test-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc libcriterion-dev lcov

      - name: Configure (Debug with coverage)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug -- -j2

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      # lcov で tests 配下を収集対象から外し、不要パスも除外
      - name: Capture coverage
        run: |
          # tests/*.gcda を最初から対象外にして収集（mismatch対策の肝）
          lcov --directory build --capture --output-file coverage.info \
               --rc geninfo_exclude='*/tests/*'

          # さらに不要パスを除去
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info

          # HTML レポート生成
          genhtml coverage.info --output-directory coverage-report

      - name: Upload coverage report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
