- name: Install deps
  run: |
    sudo apt-get update
    sudo apt-get install -y cmake gcc libcriterion-dev python3-pip
    python3 -m pip install --upgrade gcovr

- name: Configure (Debug with coverage)
  run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

- name: Build
  run: cmake --build build --config Debug -- -j2

- name: Run tests
  run: ctest --test-dir build --output-on-failure

- name: Coverage (gcovr)
  run: |
    gcovr -r . build \
      --exclude 'tests/.*' \
      --html --html-details -o coverage.html
    mkdir -p coverage-report && mv coverage.html coverage-report/index.html

- name: Upload coverage report (artifact)
  uses: actions/upload-artifact@v4
  with:
    name: coverage-report
    path: coverage-report
